window.LUNO_CONCEPTS = [
  { id: '01', name: 'Quiet glow', type: 'Compact header · Song list', className: 'glow', defaultView: 'songs',
    summary: 'A soft green atmosphere, a useful header and one clean line of playback controls.',
    background: 'A diffused green glow sits behind the header and fades into the existing charcoal background.',
    search: 'A quiet inset field gives search its own space without a heavy outline.',
    controls: 'Play and Shuffle share a single toolbar. Songs and Playlists use a simple underline.' },
  { id: '02', name: 'Cover stack', type: 'Artwork hero · Compact search', className: 'stack', defaultView: 'songs',
    summary: 'Your collection supplies the character: overlapping covers replace an empty header.',
    background: 'A rounded, green-tinted hero contains the artwork. The rest of the page stays calm.',
    search: 'Search sits immediately below the hero in a compact, full-width field.',
    controls: 'A circular Play button anchors the artwork; Shuffle is an adjacent text action.' },
  { id: '03', name: 'Collection grid', type: 'Playlist first · Two-column cards', className: 'grid', defaultView: 'playlists',
    summary: 'A visual collection with a pinned Liked Songs card and roomy playlist covers.',
    background: 'A subtle grid and green corner light give the library a sense of structure.',
    search: 'Search stays near the title. Library view and sorting sit directly underneath.',
    controls: 'Play and Shuffle become compact header actions, leaving more room for the collection.' },
  { id: '04', name: 'Soft layers', type: 'Rounded sheet · Shared action bar', className: 'layers', defaultView: 'songs',
    summary: 'A lifted content panel groups the library instead of stacking unrelated controls.',
    background: 'A green wash behind the title meets a rounded charcoal sheet below.',
    search: 'A wide borderless field belongs to the header, above the content panel.',
    controls: 'Playback, library view and sorting are arranged inside the sheet with clear spacing.' },
  { id: '05', name: 'Library index', type: 'Dense list · Alphabet navigation', className: 'index', defaultView: 'songs',
    summary: 'Fast scanning for a larger collection, with a compact header and an alphabet rail.',
    background: 'Fine horizontal rules and a restrained green haze keep the list readable.',
    search: 'An understated search line puts the query ahead of decorative chrome.',
    controls: 'Two compact playback actions sit under the title; A–Z navigation belongs to the list.' },
  { id: '06', name: 'Artwork canopy', type: 'Full-bleed hero · Floating search', className: 'canopy', defaultView: 'songs',
    summary: 'An immersive cover wall adds depth while the useful controls stay in the foreground.',
    background: 'Oversized collection artwork sits under a strong charcoal-to-green scrim.',
    search: 'A floating search field bridges the artwork header and the song list.',
    controls: 'Play and Shuffle stay visible against the hero. The library view sits below search.' },
  { id: '07', name: 'Side column', type: 'Vertical view switch · Compact rows', className: 'rail', defaultView: 'songs',
    summary: 'A slim side column moves the view switch out of the crowded top controls.',
    background: 'A vertical green glow marks the navigation column; content stays charcoal.',
    search: 'Search spans the header above the split layout.',
    controls: 'Songs and Playlists live in a labelled side rail. Play and Shuffle belong to the content.' },
  { id: '08', name: 'Library blocks', type: 'Overview tiles · Collection panel', className: 'blocks', defaultView: 'songs',
    summary: 'Large Songs and Playlists tiles make the two library views easier to understand.',
    background: 'A soft green pool of light and inset surfaces connect the tiles to Luno’s theme.',
    search: 'Search is placed first, beneath the title, before the collection overview.',
    controls: 'The overview tiles act as the view switch. A wide playback bar sits beneath them.' },
  { id: '09', name: 'One toolbar', type: 'Unified search and play · Spacious rows', className: 'toolbar', defaultView: 'songs',
    summary: 'A single useful toolbar replaces the scattered search field and playback buttons.',
    background: 'A diagonal green wash adds character behind generous, uncomplicated rows.',
    search: 'Search and Play share one rounded control surface, with a separate Shuffle action.',
    controls: 'Songs and Playlists use large text tabs. Sorting is aligned with the result count.' },
  { id: '10', name: 'Record shelf', type: 'Playlist first · Wide artwork rows', className: 'shelf', defaultView: 'playlists',
    summary: 'Wide playlist sleeves make the collection feel tactile without changing Luno’s palette.',
    background: 'Faint shelf lines and a deep green light add texture without competing with covers.',
    search: 'A compact search strip sits below a clear title and view switch.',
    controls: 'Library playback is one small header cluster. Individual sleeves remain easy to browse.' }
];
